### ISSUE TITLE
Installation failure for `CMake` 3.16.3

### ISSUE THREAD

**Issue by DavidSCN** [exadg/exadg#124]
Pulling the latest changes applied in #113 leads to a plenty of error messages with the first one being

```bash
CMake Error at applications/CMakeLists.txt:38 (ADD_SUBDIRECTORY):
  The source directory

    ~/exadg/applications/CMakeFiles

  does not contain a CMakeLists.txt file.
```

I followed the installation instruction provided in the wikis.

**Comment by peterrum** [comment]
It looks like you are attempting an in-tree build. The following line https://github.com/exadg/exadg/blob/bdaf15c3954778d98ef0c8c83594b1b075ae1779/applications/CMakeLists.txt#L37

loops over all folder incl. the generated `CMakeFiles`. My guess is that adding `IF(NOT "${SUBDIRS}" STREQUAL "CMakeFiles")` would help. Can you try this out? Alternatively, build out-of-tree ;)

**Comment by DavidSCN** [comment]
For the record: the error was independent of the build location relevant.
