### ISSUE TITLE
Provide quadrature point index in VariableCoefficients class

### ISSUE THREAD

**Issue by kronbichler** [exadg/exadg#128]
Looking at https://github.com/exadg/exadg/pull/122#discussion_r782232750, I realized that https://github.com/exadg/exadg/blob/01939cbd3441629dacd624d5cef041cbb9904db6/include/exadg/operators/variable_coefficients.h#L40-L42 hard-codes the number of quadrature points to `degree + 1`, independent of what a possible use e.g. in https://github.com/exadg/exadg/blob/01939cbd3441629dacd624d5cef041cbb9904db6/include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.cpp#L76 would request: The `quad_index` in that class could be signalling a different number of points, e.g. a 3/2 quadrature rule.

**Comment by nfehn** [comment]
@kronbichler would you like to provide a PR for this problem? It would be required here https://github.com/exadg/exadg/pull/287#issuecomment-1328771261.
