### ISSUE TITLE
Update to newer clang-format version

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#173]
Having changed to our new Ubuntu OS at LNM with clang-format version 10, I receive clang-format errors, probably because the "indent check" uses an older version.

Here we should discuss whether we want to go to a newer clang-format version, and which version to choose. Also, it would be helpful if ExaDG could provide this tool somewhat automatically in the correct version in order to take this burden from ExaDG developers (I think deal.II has a script to install clang-format automatically).

**Comment by peterrum** [comment]
> Having changed to our new Ubuntu OS at LNM with clang-format version 10, I receive clang-format errors, probably because the "indent check" uses an older version.
Here we should discuss whether we want to go to a newer clang-format version, and which version to choose. 

In deal.II, we are using v.11. I am in favor in updating clang-format but only once all relevant PRs are merged.

> Also, it would be helpful if ExaDG could provide this tool somewhat automatically in the correct version in order to take this burden from ExaDG developers (I think deal.II has a script to install clang-format automatically).

To get the old version, you can adopt https://github.com/dealii/dealii/blob/dealii-9.3/contrib/utilities/download_clang_format and for the newer version https://github.com/hyperdeal/hyperdeal/blob/master/contrib/utilities/download_clang_format.

**Comment by peterrum** [comment]
I am in particular thinking about PR #122 and #148. There is no need to cause there merge conflicts if one can wait a couple of weeks.

**Comment by nfehn** [comment]
Agree. We can wait a bit longer with clang-format. But it is also important to get these PRs merged!

**Comment by jh66637** [comment]
It might be a good time after https://github.com/exadg/exadg/pull/262
It is very likely there will be merge-conflicts for other existing PRs after this anyway. At least a lot of files and lines changed...

**Comment by jh66637** [comment]
If this is done it would be great to have it like in deal,II and hyper.deal (see https://github.com/hyperdeal/hyperdeal/tree/master/contrib/utilities):
* script which downloads correct clang-format version
* indent-all should check for the downloaded version before falling back to the system installation

I had problems with the version on my system. Thanks, @peterrum, for pointing me to the correct version :+1:

**Comment by btemuer** [comment]
@peterrum just mentioned this issue in #362. I also think that this is a good idea.

> I am in particular thinking about PR https://github.com/exadg/exadg/pull/122 and https://github.com/exadg/exadg/pull/148.

Here, #148 is merged, but #122 is still open.

> It might be a good time after https://github.com/exadg/exadg/pull/262

#262 is also merged.

Is now the right time for this?

**Comment by nfehn** [comment]
Yes, we should address this now. Any volunteer?

**Comment by peterrum** [comment]
I can do that :)
