### ISSUE TITLE
slurm script error with exadg

### ISSUE THREAD

**Issue by fab6** [exadg/exadg#180]
Hi,

the deal-9.3.3 and exadg compilation worked (did not include petsc and no trilinos yet, no fftw). In addition to  p4est I needed numdiff as local installation (at least for the second reinstallation using a slurm script). After first similar error message  (see below) I recompiled deal/p4est and exadg on the nodes via slurm script. `numdiff` was installed on the frontend.

I used for installation some available modules:
```
module load 2021a GCC/10.3.0 OpenMPI/4.1.1 CMake/3.20.1 libarchive METIS/5.1.0
```
A local quick run on the frontend works:
![image](https://user-images.githubusercontent.com/3047695/155963481-9c21adfe-841c-48bf-9193-eb4148cd13bd.png)

The slurm script looks like:
![image](https://user-images.githubusercontent.com/3047695/155963678-0e677551-b60b-45b0-bb81-ee0b3b5299f3.png)

Now when trying to run e.g. the TGV incompressible application I get an error when running using `slurm`:
```
srun: error: wn21205: tasks 0-5,7-15: Illegal instruction
srun: error: wn21205: task 6: Illegal instruction
```

I get similar error when using the complete path for the executable or e.g. `mpirun -np 16` or solely `srun`.

E.g. for `mpirun` I get
![image](https://user-images.githubusercontent.com/3047695/155966148-25e5573d-06bc-4c90-b9fa-0b11c4b6a119.png)

Do you have an advice how to get the examples running via slurm?
Thank you in advance!
Fab

**Comment by fab6** [comment]
The processor on the frontend is a intel xeon whereas the nodes have
![image](https://user-images.githubusercontent.com/3047695/155969514-9926a08d-60a5-4b67-8b4f-8e1cc197e7cf.png)

So I assume the comilation on the nodes (which I did) is important; though the error confuses me.

**Comment by kronbichler** [comment]
The `illegal instruction` exception typically means that you have compiled the code for an instruction set that is not supported by the running CPU. This happens e.g. when you set the compile flag as `-march=native` with the gcc compiler on an Intel Xeon Skylake/Cascade Lake/Ice Lake (or some desktop variants), which enables AVX-512, but then run on a CPU without AVX-512 support. From what you describe, this seems to be the case indeed. I recommend to replace `-march=native` by `-march=haswell` instead, which should generate code both compatible with Intel Xeon (assuming that the Intel Xeon is newer than 2013's Ivy Bridge, the last generation not supporting AVX2) and AMD Epyc. @nfehn I think we should either add a comment to the compile script for this, as the case is not that uncommon and inexperienced users have a really hard time to understand what goes wrong and why.

**Comment by fab6** [comment]
Thank you very much for your quick help! 
It is a bit strange, because I did actually a completely new installation of dealii and exadg on the nodes itself due to this (at least I thought), but maybe `numdiff`'s installation on the frontend destroyed it or I had some old stuff.
I will let you know when it works...

**Comment by fab6** [comment]
ok, works, now, thank you again
