### ISSUE TITLE
use cell_iterators() or active_cell_iterators()?

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#215]
We currently do not consistently use `cell_iterators()` or `active_cell_iterators()`. This might be irritating for users who do not have detailed background knowledge about dealii, users who just want to "use" ExaDG and, for example, implement their own examples taking existing ones as a template.

The typical use case is (i) to generate a grid (potentially composed of multiple elements, e.g. subdivided hyper cube/rectangle), but without any global refinements. (ii) Next, we loop over the cells (e.g. apply boundary IDs). (iii) Finally, global refinements are performed.

The question is which type of cell iterators should be used? I would argue that it does not make a difference for the use case above. However, we should take into account that `Grid::create_triangulation()` applies local and global refinements in the current implementation. @kronbichler @peterrum What do you consider more general? Is there a disadvantage if we use `cell_iterators()` always for the above use case? Assume unexperienced users switch steps (ii) and (iii) in their code. Using `active_cell_iterators()` might then lead to wrong results / problems, because coarse levels in multigrid algorithms also want to know the correct type of boundary conditions. Is this correct?

**Comment by kronbichler** [comment]
It depends on what queries are done with the iterators: If we use it for setting boundary ids, manifold ids and similar things, using `cell_iterators()` should be fine. It gets only problematic in case we query degrees of freedom or similar quantities that only live on the active cells but not on the coarser levels - in that case, the code will likely segfault (release mode) or throw some assertion. So I would agree on mostly using the `cell_iterators()` for basic manipulations, but with deviations in case some things do not work.

**Comment by nfehn** [comment]
Ok, sounds like a plan. I could make the changes and would be happy if e.g. @kronbichler could briefly check that the changes are unproblematic, in the sense that we do not introduce unnecessary (obvious) bugs.

**Comment by peterrum** [comment]
Personally, I think the safest way would be to assign the ids when the mesh has not been refined yet, i.e., `cell_iterators()` and `active_cell_iterators()`. Everything else will not work if we should AMR capabilities (and will lead to annoying bugs). Since we cannot force anyone to do it like this, I would suggest to add an assert that checks the boundary ids on all levels (possibly only in the case that AMR is requested).
