### ISSUE TITLE
No convergence with Rayleigh-Benard application

### ISSUE THREAD

**Issue by marcfehling** [exadg/exadg#237]
I tried to run the Rayleigh-Benard application with the default [input file](https://github.com/exadg/exadg/blob/master/applications/incompressible_flow_with_transport/rayleigh_benard/input.json). However, it seems like the CG solver for the `IncNS::ProjectionOperator` does not converge. Can you repeat the problem?

I am using deal.II 9.4.0. You can find the console output attached: [default.log](https://github.com/exadg/exadg/files/9039734/default.log)
 
I did not try other applications yet, so I can't say if other applications are affected as well.

**Comment by nfehn** [comment]
yes, I can confirm this. Please check the setup from #238.
