### ISSUE TITLE
Deprecation warnings because of dealii::FEEvaluation and dealii::FEFaceEvaluation

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#240]
Changes in deal.II probably cause many, many deprecation warnings in ExaDG. These should be fixed.

**Comment by kronbichler** [comment]
Yes, this should be a high-priority topic. Most are coming from https://github.com/dealii/dealii/pull/13995 where the old interfaces to `FEEvaluation`, taking boolean arguments, have been deprecated.

**Comment by jh66637** [comment]
I used the new interface in the code I wrote and can give this a try :)

**Comment by nfehn** [comment]
great! I really appreciate your enthusiasm.

**Comment by kronbichler** [comment]
> I really appreciate your enthusiasm.

Indeed. Go ahead, we're also happy to take an 80% solution and fix the remaining 20%, in case you feel stuck somewhere.

**Comment by nfehn** [comment]
Maybe it is most efficient to discuss some general aspects beforehand: I think I would keep `IntegratorFlags`

https://github.com/exadg/exadg/blob/master/include/exadg/operators/integrator_flags.h

but replace the boolean types inside. Does this make sense in your opinion, @kronbichler ?

**Comment by peterrum** [comment]
> Maybe it is most efficient to discuss some general aspects beforehand: I think I would keep IntegratorFlags

Sounds reasonable. `IntegratorFlags` is a collection of two/three `EvaluationFlag`s.
