### ISSUE TITLE
dof_handler.distribute_mg_dofs()

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#277]
What should we do with this line: https://github.com/exadg/exadg/blob/dc2c483d3ca9fe275ce5e6e268985755fcce02fc/include/exadg/poisson/spatial_discretization/operator.cpp#L134?

The if-statement checking for hypercube-elements is not the right logic in my opinion. I think we need this only for local-smoothing multigrid. Hence, we should change the if-statement accordingly, by deducing from the list of parameters whether local-smoothing multigrid is used or not.

As discussed already somewhere else (but I do not remember where), this function call would be better placed inside the multigrid preconditioner. Then, it would be intuitively clear for new developers (like @necioglu) where this is needed, i.e., we would achieve a more modular design.

@kronbichler @peterrum It would be great if you could share your opinion here so that we can solve this now.

**Comment by nfehn** [comment]
see also #133

**Comment by nfehn** [comment]
@necioglu see also the discussion here: https://github.com/exadg/exadg/pull/110#discussion_r765046008

**Comment by kronbichler** [comment]
I would simply move the code to the multigrid class, in other words do:
```
  if (!dof_handler.has_level_dofs())
    const_cast<DoFHandler<dim> &>(dof_handler).distribute_mg_dofs();
```
and delete the code here. I cannot promise I will get around to implement and test this in the next two days (given that I started looking into it in January), but I would assume it should be worth a try.

**Comment by nfehn** [comment]
I agree, @necioglu . However, the variant by @kronbichler might look more generic and we should place this code in the multigrid-preconditioner. @kronbichler Could you explain the reasoning behind your implementation and explain it in terms of local-smoothing versus global-coarsening multigrid? Also, what happens if this code would be called multiple times? For Navier-Stokes, several equations (viscous step and penalty step) might want to set up a multigrid preconditioner for the velocity dof-handler. In `SpatialOperator` we have "good control" that the function is only called once. So we have to make sure that shifting the code to multigrid cannot introduce unwanted side effects.

**Comment by kronbichler** [comment]
That's why I suggest to guard the code inside the multigrid preconditioner by the check `if (!dof_handler.has_level_dofs())` - this ensures that the enumeration is only compute if it does not yet exist.

**Comment by nfehn** [comment]
Ah, so you would additionally make sure that global-coarsening multigrid does not run into this branch?

**Comment by kronbichler** [comment]
Yes, we should only do this if necessary by the multigrid algorithm, to clarify the intent.

**Comment by nfehn** [comment]
Thanks. @necioglu, this means that we use the variant by @kronbichler but make sure to place it in the branch for local-smoothing in the `MultigridPreconditioner` (if I understand it correctly).

**Comment by necioglu** [comment]
Okay, it makes sense. 

But I have tried the code I have sent here and it doesn't seem to work out of the box. Are we sure that global coarsening doesn't need the function call `dof_handler.distribute_mg_dofs();`?

**Comment by nfehn** [comment]
I am not 100% sure. @peterrum what do you think?

**Comment by necioglu** [comment]
> Okay, it makes sense.
> 
> But I have tried the code I have sent here and it doesn't seem to work out of the box. Are we sure that global coarsening doesn't need the function call `dof_handler.distribute_mg_dofs();`?

It was an error on my end, now the basic variant works. The poisson/sine application was not using the `create_triangulation` function of the `Grid` class and therefore couldn't build the `coarse-triangulations`, although the flag was set true. This means `coarse_triangulations.size() =0` in:
https://github.com/exadg/exadg/blob/dc2c483d3ca9fe275ce5e6e268985755fcce02fc/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp#L151

Maybe something worth checking with an Assert?

**Comment by nfehn** [comment]
Yes, in this case we could assert to have at least one coarse triangulation. Regarding the size of this vector, I think it is hard to do more than asking `coarse_triangulations` for its size.

**Comment by necioglu** [comment]
This else branch in `multigrid_preconditioner_base` seems like the right place.

https://github.com/exadg/exadg/blob/97f92fdc00e514b892e167cdf2f3bcbe4f0f6a0f/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp#L455

**Comment by nfehn** [comment]
Yes, do you want to give this a try @necioglu?

**Comment by necioglu** [comment]
Yes, I just wanted to double check before I start with the changes.

**Comment by nfehn** [comment]
Note that `distribute_mg_dofs()` also occurs in other modules (convection-diffusion, structure, incompressible Navier-Stokes) which should also be removed now. Just search for all occurrences of  `distribute_mg_dofs()` in ExaDG.

**Comment by nfehn** [comment]
For me it currently looks like multigrid is creating its own dof-handlers and the function call that we currently have in `Poisson::SpatialOperator` is just left-over?

**Comment by nfehn** [comment]
I think this makes sense. In case of h-MG we have one p-level and we need to call distribute_mg_dofs().
