### ISSUE TITLE
Make global-coarsening MG work with periodic faces

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#282]
We currently have the following assert in the code: 

https://github.com/exadg/exadg/blob/97f92fdc00e514b892e167cdf2f3bcbe4f0f6a0f/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp#L447

which does not allow global-coarsening MG in case of periodic faces.

We should aim at relaxing this, i.e. we want to simulate some standard Navier-Stokes benchmarks (Taylor-Green vortex) with simplices where we (i) need global coarsening and (ii) have periodic faces.

Enabling periodic boundaries for simplex meshes (independent of using MG or not) is a different topic (which is so far not possible on the deal.II side as far as I know).

@necioglu @peterrum FYI

**Comment by necioglu** [comment]
I have also noticed some problems using  `FullyDistributed` triangulations with periodic faces. This is where it fails:

https://github.com/exadg/exadg/blob/1e124bb81f96b5f3e4cf4f4c6a96c3693bb7aba4/include/exadg/functions_and_boundary_conditions/verify_boundary_conditions.h#L41-L42

**Comment by nfehn** [comment]
@necioglu I think this is something different. Can you describe this in a separate issue? The present issue is about multigrid.

**Comment by nfehn** [comment]
see PR #389
