### ISSUE TITLE
Multigrid Preconditioner with global coarsening and h-MG fails

### ISSUE THREAD

**Issue by jh66637** [exadg/exadg#303]
As an example, see the failing test case of the flow past a sphere.

As far as I can relate, this is because the ```Grid``` class fails to build the coarse_triangulations (in function ```create_triangulation()```) . Since the creation is just a function call to a deal.II function, I suppose the function is either called with wrong arguments, a different function should be called, or something is broken inside deal.II. I am new to the whole topic of using Multigrid in deal.II, so maybe someone who is more experienced can have a look. 

The current work-around for me is to set ```MultigridType::cpMG``` instead of ```MultigridType::cphMG```.

**Comment by nfehn** [comment]
I am currently working on similar problems. Your problem might be resolved once #305 is merged.

**Comment by necioglu** [comment]
@jh66637 I am not sure, but it might be that the following line is causing the problem:
https://github.com/exadg/exadg/blob/f0cf96e3d8f7fc2376d8109927c4b5e0f7ace44f/include/exadg/solvers_and_preconditioners/multigrid/multigrid_preconditioner_base.cpp#L641
It is only called for global coarsening multigrid. You can try changing it to the following as done in #305 :
`dealii::Functions::ZeroFunction<dim,MultigridNumber>zero_function(dof_handler.get_fe().n_components());`

If this helps, we might create a small PR addressing only this issue @nfehn .

Btw, `flow_past_sphere` fails earlier for me, during the grid creation:
`Error: set_all_manifold_ids() can not be called on an empty Triangulation.`

**Comment by jh66637** [comment]
@necioglu Thanks for the tip. I updated ```ExaDG``` and changed as suggested. Unfortunately, for me, the application crashes with ```coarse_triangulations.size() > 0```.

Grid generation is working for me...

**Comment by nfehn** [comment]
But note that #305 is still not merged

**Comment by jh66637** [comment]
I just fetched the current state of #305, but I still have the same problems.

**Comment by peterrum** [comment]
> Unfortunately, for me, the application crashes with coarse_triangulations.size() > 0.

Which assert is triggered? What are you multigrid/grid settings?

**Comment by necioglu** [comment]
@jh66637 are you setting the variable `this->param.grid.create_coarse_triagulations=true` ?

**Comment by jh66637** [comment]
@necioglu: This was actually the case.

Thanks a lot for all your help :) 

I created a small PR to resolve this issue.

**Comment by jh66637** [comment]
@necioglu On my laptop, I have the same problem with the manifold IDs. On the working station I have the latest versions of deal.II and ExaDG and everything works out of the box if the parameter is set.

**Comment by necioglu** [comment]
@jh66637 no worries. 
> @necioglu: This was actually the case.
> 
> Thanks a lot for all your help :)
> 
> I created a small PR to resolve this issue.

But I don't think a PR is necessary because `use_global_caorsening` is never the default case in any application and therefore `create_coarse_triangulations ` needs to stay as false.

> @necioglu On my laptop, I have the same problem with the manifold IDs. On the working station I have the latest versions of deal.II and ExaDG and everything works out of the box if the parameter is set.

This was the only problem I have, since `use_global_caorsening` was always set false on the master. I think this might be worth creating an issue. It should be a quick fix again, because as far as I remember, the error message was something like:
`Can't set manifold ids on an empty triangulation`

**Comment by jh66637** [comment]
@necioglu I don't think an issue is needed if everything works with the most recent versions of deal and ExaDG. Or do you have the issue with this setting?

**Comment by necioglu** [comment]
@jh66637 I guess I need the latest version of dealii. No issue needed.
