### ISSUE TITLE
Output n_dofs_per_cell incorrect for Poisson with Simplex

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#304]
see https://github.com/exadg/exadg/blob/907b00ea2a54e21838e75063fcb215cade6eb4dd/include/exadg/poisson/spatial_discretization/operator.cpp#L165

@necioglu would you like to have a look at this?

**Comment by necioglu** [comment]
The variable `ndofs_per_cell` is now wrong for simplices and should be changed. Its only use is in the following line: 

https://github.com/exadg/exadg/blob/907b00ea2a54e21838e75063fcb215cade6eb4dd/include/exadg/poisson/spatial_discretization/operator.cpp#L181

I think we can replace it with the following and get rid of the variable `ndofs_per_cell`.

`print_parameter(pcout, "number of dofs per cell", fe->n_dofs_per_cell());`

I will look into it and create a PR.
