### ISSUE TITLE
Grid class stores a single mapping, cannot use global coarsening multigrid

### ISSUE THREAD

**Issue by richardschu** [exadg/exadg#322]
Connects to #320; for global coarsening multigrid, we should provide a mapping for each level. Currently, using global coarsening triggers:
The violated condition was: 
    (triangulation->is_multilevel_hierarchy_constructed())
Additional information: 
    Multigrid DoFs can only be distributed on a parallel Triangulation if
    the flag construct_multigrid_hierarchy is set in the constructor.
Sequence in lung/include/grid/create_grid.h is now:
1) create lambda function incl refinement, 2) call  create_fine_and_coarse_triangulations with lambda function, 3) apply mapping on the final grid
Or am I misunderstanding something here?

**Comment by peterrum** [comment]
@richardschu Could you post the stack trace? I am wondering where this assert is triggered.

**Comment by richardschu** [comment]
Stacktrace:
-----------
#0  /homes/wiss/schussri/dealii-candi/deal.II-master/lib/libdeal_II.so.9.5.0-pre: dealii::internal::DoFHandlerImplementation::Policy::ParallelDistributed<3, 3>::distribute_mg_dofs() const
#1  /homes/wiss/schussri/dealii-candi/deal.II-master/lib/libdeal_II.so.9.5.0-pre: dealii::DoFHandler<3, 3>::distribute_mg_dofs()
#2  build/applications/lung/solver_poisson: ExaDG::Lung::DeformedMesh<3, double>::initialize(std::map<unsigned int, std::unique_ptr<ExaDG::DeformTransfinitelyViaCylinder<3>, std::default_delete<ExaDG::DeformTransfinitelyViaCylinder<3> > >, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::unique_ptr<ExaDG::DeformTransfinitelyViaCylinder<3>, std::default_delete<ExaDG::DeformTransfinitelyViaCylinder<3> > > > > > const&)
#3  build/applications/lung/solver_poisson: void ExaDG::Lung::create_grid<3>(std::shared_ptr<ExaDG::Grid<3> >, ExaDG::GridData const&, std::shared_ptr<TriangulationParameters const>, unsigned int const&, unsigned int const&, unsigned int&)
#4  build/applications/lung/solver_poisson: ExaDG::Poisson::Application<3, 1, double>::create_grid()
#5  build/applications/lung/solver_poisson: ExaDG::Poisson::Driver<3, double>::setup()
#6  build/applications/lung/solver_poisson: void ExaDG::run<3, double>(std::vector<ExaDG::SolverResult, std::allocator<ExaDG::SolverResult> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int, unsigned int, ompi_communicator_t* const&, bool)
#7  build/applications/lung/solver_poisson: main
--------------------------------------------------------

**Comment by richardschu** [comment]
> @richardschu Could you post the stack trace? I am wondering where this assert is triggered.
I put my current version in a merge request on gitlab for you to test!

**Comment by peterrum** [comment]
I think this is the problem: https://gitlab.lrz.de/exadg/exadg-applications/-/blob/master/applications/lung/include/grid/mapping/initialize_mapping.h#L47. It can be called only, if the levels have been constructed in `Triangulation`.  Can we call `is_multilevel_hierarchy_constructed()` to check if this is indeed the case?

**Comment by nfehn** [comment]
Please consider PR #443. Let us then discuss how to proceed with this issue.
