### ISSUE TITLE
Why re-creating the finest triangulation in case of global-coarsening MG?

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#329]
See https://github.com/exadg/exadg/blob/4cd65d5c8973e4f3da199f3906155571b4c66191/include/exadg/grid/grid_utilities.h#L187-L192

I think on the finest mesh we do not have to re-create the triangulation via `lambda_create_triangulation`, but could instead let the first element of the vector point to the fine triangulation object created before.

**Comment by peterrum** [comment]
Correct, this is what https://github.com/exadg/exadg/blob/4cd65d5c8973e4f3da199f3906155571b4c66191/include/exadg/grid/grid_utilities.h#L148 is doing :+1:

**Comment by necioglu** [comment]
I will take care of this!
