### ISSUE TITLE
NormalFluxCalculator does not work correctly for continuous Galerkin

### ISSUE THREAD

**Issue by gilrrei** [exadg/exadg#340]
Do we need something special for boundary face loops for CG vs DG? The result seem to be correct for DG.

**Comment by peterrum** [comment]
> NormalFluxCalculator does not work correctly for continuous Galerkin

What does this mean? Are the results wrong, zero, ...!?

**Comment by nfehn** [comment]
yes, wrong sign, factor of 3 larger, sometimes even a bigger factor

**Comment by nfehn** [comment]
we also missed an update_ghost_values() which @gilrrei will suggest as PR indepedently of the present issue (at least I believe it is something independent and just a parallel bug that needs to be solved)

**Comment by peterrum** [comment]
@gilrrei Suggestion: run debug mode. This way the missing `update_ghost_values()` would have been easy to spot.

**Comment by nfehn** [comment]
do we need `read_dof_values_plain()` for continuous Galerkin?

**Comment by peterrum** [comment]
> do we need read_dof_values_plain() for continuous Galerkin and would this then be the general solution working correctly for both CG and DG,

This is partly the solution. `FEEvaluation::read_dof_values` does two things: 1) read the relevant cell DoFs and 2) apply the constraints. If you do use `FEEvaluation::read_dof_values`, it only reads the cell-local DoFs without resolving the constrains. You need to this manually by using `AffineConstraints::distribute()`. If you don't do this, homogegenous DBC, ... are missing...

**Comment by nfehn** [comment]
I understand this comment only partly: where is the function …_plain() or do you suggest a solution without …_plain()?

**Comment by peterrum** [comment]
I have updated the comment...

**Comment by nfehn** [comment]
Then I do not understand why we got the correct results with the variant _plain()?
