### ISSUE TITLE
Question on application of periodic boundary conditions on fullydistributed triangulations 

### ISSUE THREAD

**Issue by necioglu** [exadg/exadg#346]
I have noticed some problems using `FullyDistributed` triangulations with periodic faces. This is where it fails for the Incompressible Navier-Stokes, Taylor-Green vortex application: 

https://github.com/exadg/exadg/blob/1e124bb81f96b5f3e4cf4f4c6a96c3693bb7aba4/include/exadg/functions_and_boundary_conditions/verify_boundary_conditions.h#L41-L42

**Comment by nfehn** [comment]
Is the problem fullydistributed or simplex?

**Comment by necioglu** [comment]
> Is the problem fullydistributed or simplex?

The problem is with fullydistributed. I have double checked this right now as well. When I switch to fulldistributed, using hypercubes, the run fails with a segmentation fault in the above given location. When I go back to distributed, it works fine.

**Comment by peterrum** [comment]
p:f:T supports periodic faces. See https://github.com/dealii/dealii/blob/master/tests/fullydistributed_grids/copy_serial_tria_04.cc

My guess is that you did not apply pbc to p:f:T, i.e., you need to apply it to the original (serial) tria and the distributed one.

> simplex?

That won't work.

**Comment by nfehn** [comment]
I understand @peterrum's  comment in a way that we need to double-check once more and potentially adjust the title of this issue.

**Comment by peterrum** [comment]
> I understand @peterrum's comment in a way that we need to double-check once more and potentially adjust the title of this issue.

I believe @necioglu that in ExaDG pbc+pft is not working. But this probably an issue on ExaDG side. One needs to double check if pbc is applied to the all pft instances (including the ones on the levels).

**Comment by nfehn** [comment]
> I believe @necioglu that in ExaDG pbc+pft is not working. But this probably an issue on ExaDG side. One needs to double check if pbc is applied to the all pft instances (including the ones on the levels).

It looks like this is simply not implemented, see issue #387. I think the problem seems to be related neither to simplex nor to `fullydistributed::Triangulation`, but to the use of `GridUtilities::create_triangulation()` and `lambda_create_triangulation()` functionality, which does not support periodic boundaries. If you agree, @necioglu, we can probably close the present issue.

**Comment by necioglu** [comment]
I agree, I will close this. 

> When I go back to distributed, it works fine.

Maybe while working on #387, keep in mind the above observation I have made.
