### ISSUE TITLE
Contributing guidelines

### ISSUE THREAD

**Issue by btemuer** [exadg/exadg#358]
The community developing ExaDG seems to be of considerable size but there is no `CONTRIBUTING.md` in the repo yet. 

I wanted to ask if we wish to have at least some simple contributing guidelines on the basic requirements on issues, commits, and PRs.

If yes, I would volunteer to initiate the efforts.

**Comment by peterrum** [comment]
In principal, I agree. What would you add compared to our wiki https://github.com/exadg/exadg/wiki?

**Comment by btemuer** [comment]
I would condense the information on working with git and the coding conventions in the wiki, combine them and also add more detailed information on what we expect issue and PR descriptions to look like, what we want to see in commit messages (e.g. a linked issue number), how to incorporate changes after a PR review, with an additional commit or with a clear history, if a branch should always be rebased to the latest master commit, etc. Additional points may be on whom and how to ask for reviews, assigning labels incl. draft status, reminding to squash commits, run tests on a local machine before pushing, and so on. This kind of things, basically.

Or maybe we want to keep things more relaxed, my experience was just that having this information upfront is helpful, especially for newcomers.

**Comment by peterrum** [comment]
> I would condense the information on working with git and the coding conventions in the wiki, combine them and also add more detailed information on what we expect issue and PR descriptions to look like, what we want to see in commit messages (e.g. a linked issue number), how to incorporate changes after a PR review, with an additional commit or with a clear history, if a branch should always be rebased to the latest master commit, etc. Additional points may be on whom and how to ask for reviews, assigning labels incl. draft status, reminding to squash commits, run tests on a local machine before pushing, and so on. This kind of things, basically.
> 
> Or maybe we want to keep things more relaxed, my experience was just that having this information upfront is helpful, especially for newcomers.

Till now mainly three persons contributed so we never needed to formalize the workflow. But if you think it helps, feel free to setup a guideline. Now is the right time as long as you are new!

**Comment by nfehn** [comment]
I appreciate your initiative. Thanks!

> Or maybe we want to keep things more relaxed, my experience was just that having this information upfront is helpful, especially for newcomers.

I agree here that we want to keep things somewhat relaxed and not burden new developers with many rules to fulfill. So I think a contributing file is good, but we should come up with a minimal solution for now.
