### ISSUE TITLE
Problem with indent-all script

### ISSUE THREAD

**Issue by btemuer** [exadg/exadg#371]
I think there is a problem with our indent-all script, introduced in #364.

https://github.com/exadg/exadg/blob/85324e74d187c1639fbd8be48a5ff3bfd11bbf4c/contrib/utilities/indent-all#L30

means that the script can only be executed inside `contrib/utilities/`, but then the clang-format doesn't find the source files.

At least I couldn't get it to work.

Writing 

```
cf=contrib/utilities/programs/clang-11/bin/clang-format 
```

and executing from the top-level directory would be my solution.

**Comment by richardschu** [comment]
I downloaded clang somewhere else and used this folder only as "inspiration", but I guess this is a fool's workaround ... @peterrum ?
