### ISSUE TITLE
Cellwise inverse mass operator not available for simplices

### ISSUE THREAD

**Issue by necioglu** [exadg/exadg#372]
The cellwise inverse mass operator of dealii is not available for non-tensor product elements, e.g. simplices:

https://github.com/dealii/dealii/blob/master/include/deal.II/matrix_free/evaluation_kernels.h#L5601-L5603

This is why, I am implementing a solution for this in ExaDG, using `BlockJacobiPreconditioner` or `SolverCG`. This solution can be removed, when dealii offers the functionality.

**Comment by kronbichler** [comment]
The current form of `CellwiseInverseMassMatrix` will not be applicable to simplex elements: The algorithm relies on a change of basis into the basis of polynomials defined in the quadrature points, which is diagonal, something we described in Sec. 4.4.1 of https://doi.org/10.1002/nme.5137. For a basis change, one needs the same number of quadrature points and polynomials, and one needs orthogonality of polynomials in the latter points. Both these properties can't be established on simplices.

The right approach is to compute the cellwise mass matrix explicit and invert it (or perform an LU decomposition, as not all tetrahedral basis functions are well-conditioned enough to warrant an inversion). This might in principle increase memory consumption quite considerably, but the good thing is that tetrahedral elements with straight edges are subject to an affine mapping, so one would only need to store a single matrix (possibly including a set of matrices close the boundary) and a single factor. This makes the overall algorithm quite efficient. This is some kind of `BlockJacobiPreconditioner`, but it should be augmented with similarity detection in the long run to keep the memory consumption and transfer in check. We've done these things several times in deal.II, most recently in this code here: https://github.com/dealii/dealii/blob/a9cb77a3b30409b23cda59258cccee5b03cca739/include/deal.II/lac/tensor_product_matrix.h#L1107-L1139

`SolverCG` is also possible, but likely slower than the other alternative.

**Comment by necioglu** [comment]
> but it should be augmented with similarity detection in the long run to keep the memory consumption and transfer in check.

This is good to keep in mind! Currently, on my local implementation, I perform an LU decomposition and save every matrix. When I am done with this, I will check the similarity detection. 

> `SolverCG` is also possible, but likely slower than the other alternative.

Yes, I agree. Using `SolverCG` was part of the step-by-step approach. I think in the end we will leave it out and only rely on inverting the cell matrices.

**Comment by nfehn** [comment]
But we should keep in mind that simplex is limited to degree=1,2 for now. The picture might change for higher degrees! For now, it would be good if you could measure whether the mass matrix inversion is relevant for the overall performance for incompressible Navier-Stokes (before addressing aspects such as similarity detection), in order to prioritize topics for the next weeks.
