### ISSUE TITLE
Dynamic cast of a triangulation to p:d:T

### ISSUE THREAD

**Issue by necioglu** [exadg/exadg#375]
Maybe I am missing something here but why are we doing a dynamic cast to a `p:d:T`?
https://github.com/exadg/exadg/blob/d3c21325476fad9eed77e335ac78da17787ec207/include/exadg/poisson/preconditioners/multigrid_preconditioner.cpp#L103-L105
When I use a a fullydistributed or a serial triangulation the cast seems to fail and I get a segmentation fault from the `Categorization::do_cell_based_loops`, which tries to use `tria`.

**Comment by peterrum** [comment]
Just remove the cast.
