### ISSUE TITLE
GridUtilities::create_triangulation() does not take into account periodic faces

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#387]
The newly introduced utility functions in `GridUtilities` do not take into account periodic faces. It seems as if we need to extend the interfaces such that `lambda_create_triangulation` can impose/set periodic faces.

This raises the question whether the `Grid` class (see https://github.com/exadg/exadg/blob/master/include/exadg/grid/grid.h) is well-designed at all? It currently looks like

```c++
class Grid
{
  ....

  std::shared_ptr<dealii::Triangulation<dim>> triangulation;

  std::vector<std::shared_ptr<dealii::Triangulation<dim> const>> coarse_triangulations;

  PeriodicFaces periodic_faces;

  std::shared_ptr<dealii::Mapping<dim>> mapping;
}
```

- For global coarsening multigrid, I assume we need a vector of `PeriodicFaces`, right? See also issue https://github.com/exadg/exadg/issues/282.
- Issue https://github.com/exadg/exadg/issues/322 points to similar problems in terms of mappings for global-coarsening multigrid.

SUGGESTION: Wouldn't it make more sense to design the `Grid` class the following way:

```c++
class Grid
{
  ....

  std::shared_ptr<dealii::Triangulation<dim>> triangulation;

  PeriodicFaces periodic_faces;

  std::shared_ptr<dealii::Mapping<dim>> mapping;
}
```
and then pass `Grid fine_grid` as well as `std::vector<Grid> coarse_grids` to multigrid (for global-coarsening multigrid) as well as to the grid utility functions and `lambda_create_triangulation()`. With this design, a `Grid` refers to a single multigrid level. It is essentially a struct grouping together `triangulation`, `periodic_faces`, `mapping`.

This is somewhat a prerequisite to proceed with #385 and #282, which is why I consider this of HIGH priority.

@kronbichler @peterrum @bergbauer @richardschu Please share your opinion.

**Comment by nfehn** [comment]
I discussed this topic with @bergbauer and we believe we should go in the direction described here. I am going to start and see if this turns out advantageous.

**Comment by kronbichler** [comment]
This sounds reasonable to me. We need to see how information we would need to carry around in addition for multigrid, but from what I see in #389, there seems to be a good solution.

**Comment by richardschu** [comment]
Makes sense to me - I am happy to provide a mapping for each coarse level and not only for the finest one. For now, I only used uniform refinement, so 'global_coarsening' or 'local_smoothing' do not make a difference. But soon, this should become important ; ). That this enables periodic faces is for me a (particularly nice) side effect.
