### ISSUE TITLE
ExaDG fails to configure due to changes in CMake configuration in deal.II

### ISSUE THREAD

**Issue by bergbauer** [exadg/exadg#392]
ExaDG fails to configure tests and executables probably because of https://github.com/dealii/dealii/pull/14491

Failing output looks like this:
https://github.com/exadg/exadg/actions/runs/4488251375/jobs/7892619113

Affected cmake macros in ExaDG are:

- https://github.com/exadg/exadg/blob/master/cmake/macros/macro_exadg_pickup_tests.cmake
- https://github.com/exadg/exadg/blob/master/cmake/macros/macro_exadg_pickup_exe.cmake

**Comment by bergbauer** [comment]
The pipeline uses the deal.II `master-focal` version from dockerhub https://hub.docker.com/r/dealii/dealii/tags. You can check out the docker container to check the hash or look at the deal.II docker actions, which job pushed an image last.

**Comment by jh66637** [comment]
I can not reproduce the issue on my local machine. I have no idea where the difference stems from.

**Comment by nfehn** [comment]
what is the status of this issue?

**Comment by jh66637** [comment]
I think ths was fixed with https://github.com/dealii/dealii/pull/14962
