### ISSUE TITLE
Are these variable names wrong?

### ISSUE THREAD

**Issue by btemuer** [exadg/exadg#398]
Hey, I was looking around in the viscous kernel in `IncNS`, and came across this:

https://github.com/exadg/exadg/blob/d5ccbb13faafca73e84da085487f23199eef96dc/include/exadg/incompressible_navier_stokes/spatial_discretization/operators/viscous_operator.h#L408-L415

The variable `gradient_flux` is then what's returned from this function. The same but in reverse is the case for the `calculate_gradient_flux()` method. Is this on purpose or just mixed up?

**Comment by richardschu** [comment]
To me it is not obvious. Actually, that is more confusing than anything else? I guess one could just name the local variable `flux` and that's it?

**Comment by nfehn** [comment]
I don't remember actually. I am fine with just `flux` in the function implementation. Of course, in the cell/face loops, we should make sure that the names `value_flux`/`gradient_flux` are reasonable as well.
