### ISSUE TITLE
suggest-override compiler warnings

### ISSUE THREAD

**Issue by btemuer** [exadg/exadg#399]
I started to get a lot of compiler warnings with `-Wsuggest-override` for functions that actually do override but are not marked `override`. Just curious why I wasn't getting these warnings before. Does anybody else have this issue? I think we would want to sort these warnings out.

**Comment by bergbauer** [comment]
I get the warnings, too. I think we should be explicit and mark these functions `override` or `final` where appropriate.

**Comment by SudarshanHV** [comment]
Hi there @btemuer and @bergbauer. This happens as override keyword was introduced recently.  This could be a low effort commit that can be a good first issue for me. Let me know, if the warnings are removed. Otherwise, you can assign it to me, will be glad to work on it!

**Comment by btemuer** [comment]
Sure @SudarshanHV ! Please be welcome to do it, these warnings are really annoying!

**Comment by SudarshanHV** [comment]
Will be glad to work on them, so is there some specific folder where you want me to get started? Also you guys just use a normal VSCode editor for the warnings is it?

**Comment by btemuer** [comment]
I don't think it matters where you start, suit yourself. I'm using CLion for development in ExaDG.

**Comment by SudarshanHV** [comment]
@nfehn Not yet. I had to go through the exADG docs and set the repo up
Any specific reason for the question?

**Comment by nfehn** [comment]
It's just that I'd like the problem to be solved soon. @SudarshanHV What do you think is a reasonable time frame for you to make these changes?

**Comment by SudarshanHV** [comment]
It might take a week easily, as I'll be occupied with a few other tasks. Let me know if that's not feasible.

**Comment by nfehn** [comment]
If you don't mind, I could take over this issue, because the many warnings currently hinder other developments so that I want to get it solved asap.

**Comment by SudarshanHV** [comment]
Sure! Feel free to solve the issue!

**Comment by nfehn** [comment]
I've started today and hope to be able to open a PR soon!
