### ISSUE TITLE
Periodic Boundary Conditions and Local Smoothing Multigrid

### ISSUE THREAD

**Issue by jh66637** [exadg/exadg#407]
Running the fda_benchmark problem with precursor leads to a segmentation fault with the current master. As far as I can see, this is related to changes in the multigrid implementation. It seems that periodic boundary conditions are not covered anymore. 

@necioglu @nfehn

**Comment by nfehn** [comment]
There was this PR #389 on periodic faces for multigrid. Do you use the "global coarsening" multigrid variant?

**Comment by jh66637** [comment]
Thanks for pointing this out. The FDA benchmark is using the default local smoothing multigrid variant. So I think it is unrelated to the PR.

**Comment by jh66637** [comment]
You are right. The turbulent channel test case is probably the better example. I checked it and the segfault happens there as well. 
I moved to the code version before https://github.com/exadg/exadg/pull/389 got merged. The problem happens there already. I will try to find the last version where it worked and keep you posted.
