### ISSUE TITLE
Tests are failing if HDF5 (optional dependency) is not installed

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#419]
HDF5 is declared an optional dependency. However, the tests are failing without hdf5 (at least in my case) with the message "deal.II is not compiled with HDF5!". I consider this a contradiction that needs to be resolved  (since testing is essential/mandatory, rendering hdf5 a required dependency).

I suggest to exclude hdf5-related content from testing.

**Comment by nfehn** [comment]
could someone confirm this?

**Comment by jh66637** [comment]
@nfehn I have a suspicion. Are all tests failing, or only the turbulent channel test case?

**Comment by nfehn** [comment]
> I redefined `#ifdef DEAL_II_WITH_HDF5``to something that does not exist.

So you have written e.g. `#ifdef DEAL_II_WITH_ABCD` in all the places in the ExaDG-code (.h/.cpp files) where we had `#ifdef DEAL_II_WITH_HDF5` before, but all the tests are still running?

**Comment by jh66637** [comment]
Exactly

**Comment by nfehn** [comment]
@jh66637 PR #632 shows/states that `PointwiseOutputGeneratorBase<dim, Number>::setup_base()` with `AssertThrow(false, ...)` is entered always in the current master branch if one has not compiled with HDF5, see https://github.com/exadg/exadg/blob/6f6bf8c80aa848fcdfe7afcc5e043d3d768e3025/include/exadg/postprocessor/pointwise_output_generator_base.cpp#L149

When looking at the code, this actually makes sense to me. So could you discuss your point of view in the context of PR #632?

**Comment by jh66637** [comment]
After building everything from scratch, I can reproduce the issue. I can confirm that  https://github.com/exadg/exadg/pull/632 fixes it.

**Comment by richardschu** [comment]
oh nice!
that saves me some time :)
Thank you @jh66637
