### ISSUE TITLE
Test on Poiseuille with parabolic inflow is failing

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#431]
Could this be due to recent changes in dealii/master?

Any ideas on this?

**Comment by nfehn** [comment]
could https://github.com/dealii/dealii/pull/15183 be the origin?

**Comment by kronbichler** [comment]
https://github.com/dealii/dealii/pull/15183 changes the roundoff behavior, so it could be a cause if the test is extremely sensitive. I could not reproduce on my machine (compiler is `clang++-16`, so probably different from your configuration), running tests shows
```
100% tests passed, 0 tests failed out of 38
```
Can you post what kind of error you are obtaining, i.e., where the code fails, to inspect it more closely?

**Comment by nfehn** [comment]
you could e.g. look at the failing checks in PR #351
