### ISSUE TITLE
`shared_ptr` to function is passed into the FunctionEvaluator

### ISSUE THREAD

**Issue by btemuer** [exadg/exadg#439]
- incurs overhead for reference counting,

- the `FunctionEvaluator` does not manipulate the pointer (in terms of ownership), so the object should actually be passed in, not the pointer.

**Comment by nfehn** [comment]
I want to add some general ideas from my side, mainly with a focus on software design:

- In terms of software design, the goal is to write code free of `&var`, `*var`, `&(*var)`, `*(&var)`, etc.
- this can be achieved through consistent use of value or pointer semantics
- if both value and pointer semantics have the same flexibility in the code, I agree to prefer value semantics
- In the context of some/many use cases in ExaDG, I see also advantages for pointer semantics: (i) often, we cannot initialize variables during construction of an object, (ii) pointer semantics allow dynamics casts (which we do not want to use, of course, but pragmatically spoken, we have them here and there as many other code projects have them as well). In case of utility functions called at many places in a code, the dynamic cast can be placed (a) inside the implementation of the function and (b) the same function  can even deal with many types of derived classes. In case of value semantics, the cast needs to be done on the calling side (at potentially many places in the code). To distinguish between different derived classes, `switch`/`if-else` statements need to be introduced on the calling side (so the same lines of code at potentially many places).
- I can not give quantitative numbers on the "overhead for reference counting" mentioned above. What is the concrete overhead in terms of performance?

Having said this, I think it needs to be a case-by-case decision how to write code in ExaDG.
