### ISSUE TITLE
Multigrid transfer should provide partitioners

### ISSUE THREAD

**Issue by kronbichler** [exadg/exadg#462]
As initially written in https://github.com/exadg/exadg/issues/453#issuecomment-1570333596), we should not have arrived in the branch that uses the internal temporary vector on the finest level (such as c-transfer or p-transfer). We should initialize the transfers with partitioners from the underlying MatrixFree objects, in order avoid copying data back and forth.

**Comment by nfehn** [comment]
Partitioners should be provided here https://github.com/exadg/exadg/blob/cd7959276ba27849ddc787e4d63168a2a6ff822e/include/exadg/solvers_and_preconditioners/multigrid/transfers/mg_transfer_global_coarsening.cpp#LL114C84-L114C84
