### ISSUE TITLE
Interface coupling broken?

### ISSUE THREAD

**Issue by jh66637** [exadg/exadg#482]
Running `./applications/fluid_structure_interaction/cylinder_with_flag/solver ../applications/fluid_structure_interaction/cylinder_with_flag/input_aitken.json` crashes in `ContainerInterfaceData::get_data()`
1) Can someone confirm this?
2) @nfehn Do you have any clue where this comes from? Might be due to https://github.com/exadg/exadg/pull/442, but I might have missed commits dealing with this.

**Comment by richardschu** [comment]
Regarding 1.: as far as I can tell this does not depend on the coupling method (Aitken or IQN-ILS).
My last merge with master prior to GAMM was on the 11th of May, hence the breaking change should originate prior!
I will propose a very basic test (pressure pulse in a pipe with 10 time steps or whatnot) in correspondance with @nfehn once we have found the source of this.

**Comment by jh66637** [comment]
@richardschu Thanks for looking into this. 

I completely agree. I used the Aitken input file only because of https://github.com/exadg/exadg/pull/483.

**Comment by nfehn** [comment]
I currently suspect it is the order in which things are set up in the FSI driver. I will have a closer look.

**Comment by nfehn** [comment]
see https://github.com/exadg/exadg/pull/442/files#r1221464603

**Comment by nfehn** [comment]
I will open a PR soon ...

**Comment by jh66637** [comment]
@nfehn That was fast, thank you :)
