### ISSUE TITLE
Introduce utility function for creating quadrature objects similar to #513

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#517]
In analogy to PR #513 for `FiniteElement`.

@kronbichler regarding quadrature rules for `MatrixFree`, we can always write `<dim>`, right? At some places I think we write `<1>` in the code.

**Comment by kronbichler** [comment]
Yes, it should work, because we use `quad_in.get_tensor_basis()[0]` in `MatrixFreeFunctions::ShapeInfo::reinit()`.
