### ISSUE TITLE
Check consistency of InverseMassOperator for ALE problems

### ISSUE THREAD

**Issue by nfehn** [exadg/exadg#601]
In some cases, we use a block-Jacobi preconditioner to represent the action of the inverse mass operator for DG methods (e.g. simplex elements, but possibly also for hexahedral elements), see https://github.com/exadg/exadg/blob/ac70ca39cc205cfdf1e5d1ecb7a8211ad4e119e8/include/exadg/operators/inverse_mass_operator.h#L106-L140

However, for problems with moving meshes (ALE), the block matrices are no longer correct since they are not updated over time in the current implementation (and there are also no mechanisms in the code that check this), so that it might happen that the inverse mass operator (which has to be the correct or exact inverse of the mass operator) is wrong.

@kronbichler @richardschu do you agree?

**Comment by richardschu** [comment]
Good catch!
As far as I know, we store element-wise factorizations in the preconditioner or setup element-wise matrices for the element Krylov solvers, right? If the mapping and hence the mass matrix change drastically, the block-inverse mass matrices are merely approximations of the inverse mass. One has to, but might also get away with not calling the appropriate `setup` every mesh update ... not doing it after initial setup seems too much of an "approximation".
