### ISSUE TITLE
AdditiveSchwarz preconditioner not working in structure module

### ISSUE THREAD

**Issue by richardschu** [exadg/exadg#655]
I stumbled upon the issue regarding the `AdditiveSchwarz` preconditioner when looking at #652
Issue #652 (steady linear elasticity case) is fixed via #654, but the problem with the AS prec is that after one initial use it becomes invalid.
See the table in
https://github.com/exadg/exadg/issues/652#issuecomment-2018784445
and the stacktrace in
https://github.com/exadg/exadg/issues/652#issuecomment-2018785493

Probably the update is not done correctly as well here, or the internal state variables are not updated correctly.
@bergbauer could you comment on that guess of mine, I think you implemented that, right?
... I can search for the bug if you agree that something like this could be the reason.
I further assume that in the Poisson module this did not come up, since we do a single solve (similar to the working steady linear case, as seen in https://github.com/exadg/exadg/issues/652#issuecomment-2018784445).

**Comment by richardschu** [comment]
again, this is more a reminder for myself to fix this. But any hints are appreciated.

**Comment by bergbauer** [comment]
It seems like the update is not done correctly as you guessed. What the error message says is that we try to factorize a matrix which is already factorized. For an update we need to first set the matrices and then factorize them.

**Comment by richardschu** [comment]
exactly the fix I have in my branch rn
- I am compiling and testing asap
thanks for the help ;)

**Comment by richardschu** [comment]
The problem is the `matrices.resize()`, where we do not discard the vector entries, so some matrices are factorized in the vector.
So the `reinit()` on the `lapack_matrix' should do the trick :+1:
